#!/usr/bin/env bash
# Sample Deploy Assistant runner.
# Inspects the current git repo, records gates, writes a markdown report.
# Does not deploy, SSH, or read secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSISTANT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPORT_DIR="${ASSISTANT_DIR}/reports"
mkdir -p "${REPORT_DIR}"

fail() {
  echo "NO-GO: $*" >&2
  exit 1
}

command -v git >/dev/null 2>&1 || fail "git is required"
cd "${ROOT}"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || fail "not a git repository"

SHA="$(git rev-parse HEAD)"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ -z "$(git status --porcelain)" ]]; then
  TREE="clean"
else
  TREE="dirty"
fi
WHEN="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
STAMP="$(date -u +"%Y%m%dT%H%M%SZ")"
REPORT="${REPORT_DIR}/deploy-${STAMP}.md"

echo "==> pre-flight"
echo "    sha=${SHA}"
echo "    branch=${BRANCH}"
echo "    tree=${TREE}"

PREFLIGHT="PASS"
LINT="SKIP"
TESTS="SKIP"
BUILD="SKIP"
VERIFY="SKIP"

echo "==> gates"
echo "    lint/tests/build: SKIP (this sample repo has no app toolchain)"
echo "    skip is recorded in the report; it is not a silent pass"

echo "==> smoke"
SMOKE="PASS"
for required in README.md report-template.md run.sh; do
  if [[ ! -f "${ASSISTANT_DIR}/${required}" ]]; then
    echo "    missing ${required}" >&2
    SMOKE="FAIL"
  fi
done
echo "    smoke: ${SMOKE}"

if [[ "${PREFLIGHT}" == "PASS" && "${SMOKE}" == "PASS" ]]; then
  DECISION="GO"
else
  DECISION="NO-GO"
fi
echo "==> decision: ${DECISION}"

cat > "${REPORT}" <<EOF
# Deploy report

- **When:** ${WHEN}
- **Git SHA:** \`${SHA}\`
- **Branch:** \`${BRANCH}\`
- **Tree:** ${TREE}
- **Target:** sample (no remote)
- **Operator decision:** ${DECISION}

## Gates

| Step | Result | Notes |
|---|---|---|
| preflight | ${PREFLIGHT} | git metadata recorded |
| lint | ${LINT} | no app linter in this sample repo |
| tests | ${TESTS} | no test runner in this sample repo |
| build | ${BUILD} | no build step in this sample repo |
| smoke | ${SMOKE} | required sample files exist |
| post-deploy verify | ${VERIFY} | no remote target |

A \`FAIL\` anywhere required is a NO-GO. \`SKIP\` is allowed only with a written reason.

## Smoke

- Check: \`deploy-assistant/README.md\`, \`report-template.md\`, and \`run.sh\` exist
- Result: ${SMOKE}

## Rollback

\`\`\`sh
echo "rollback candidate: ${SHA}"
echo "sample runner made no remote changes"
\`\`\`

## Notes

Generated by \`deploy-assistant/run.sh\`. Do not paste tokens, emails, or home-machine paths into this file.
EOF

echo "==> wrote deploy-assistant/reports/deploy-${STAMP}.md"

if [[ "${DECISION}" != "GO" ]]; then
  fail "gates did not pass"
fi
